<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">divideTime</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ci8vIHBpcGVsaW5lCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7ClN0cmluZyBzZGF5PSIiOwpTdHJpbmcgc0hvdXI9IiI7ClN0cmluZyBzbWludXRlPSIi
OwpTdHJpbmcgc2Rpdj0iIjsKIGxvbmcgc2VjPTA7CmludCBpZGF5PTA7IAoKaW50IGlIb3VyPTA7
CgppbnQgaW1pbnV0ZT0wOwoKaW50IGlkaXY9MDsKCmlmIChwaXBlbGluZUN1cnNvci5maXJzdCgi
c3VtRGF5IikpCnsKCXNkYXkgPSAoU3RyaW5nKSBwaXBlbGluZUN1cnNvci5nZXRWYWx1ZSgpOwp9
CgppZiAocGlwZWxpbmVDdXJzb3IuZmlyc3QoInN1bUhvdXIiKSkKewoJc0hvdXIgPSAoU3RyaW5n
KSBwaXBlbGluZUN1cnNvci5nZXRWYWx1ZSgpOwp9CgppZiAocGlwZWxpbmVDdXJzb3IuZmlyc3Qo
InN1bU1pbiIpKQp7CglzbWludXRlID0gKFN0cmluZykgcGlwZWxpbmVDdXJzb3IuZ2V0VmFsdWUo
KTsKfQppZiAocGlwZWxpbmVDdXJzb3IuZmlyc3QoImRpdmlzb3IiKSkKewoJc2RpdiA9IChTdHJp
bmcpIHBpcGVsaW5lQ3Vyc29yLmdldFZhbHVlKCk7Cn0KCmlmIChzZGl2LmVxdWFscygiIikgfHwg
c2Rpdi5lcXVhbHMoIjAiKSkKCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJFcnJvciIpOwpp
ZiAoc2RheSE9ICIiKQppZGF5PUludGVnZXIucGFyc2VJbnQoc2RheSk7CgppZiAoc0hvdXIhPSAi
IikKaUhvdXI9SW50ZWdlci5wYXJzZUludChzSG91cik7CgppZiAoc21pbnV0ZSE9ICIiKQppbWlu
dXRlPUludGVnZXIucGFyc2VJbnQoc21pbnV0ZSk7CgoKIGlkaXY9SW50ZWdlci5wYXJzZUludChz
ZGl2KTsKCnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsKCnRyeSB7CgpzZWM9IChpZGF5ICogODY0
MDApICsgKGlIb3VyKjM2MDApICsgKGltaW51dGUqNjApOwoKc2VjLz1pZGl2OwoKU3RyaW5nIGRp
c3BsYXlUaW1lRGF5ID0gTG9uZy50b1N0cmluZyhzZWMvODY0MDApOwoKc2VjID0gc2VjICUgODY0
MDA7CgpTdHJpbmcgZGlzcGxheVRpbWVIciA9IExvbmcudG9TdHJpbmcoc2VjLzM2MDApOwpzZWMg
PSBzZWMgJSAzNjAwOwoJCVN0cmluZyBkaXNwbGF5VGltZU1pbiA9IExvbmcudG9TdHJpbmcoc2Vj
LzYwKTsKc2VjID0gc2VjICUgNjA7CgkJU3RyaW5nIGRpc3BsYXlUaW1lU2VjID0gTG9uZy50b1N0
cmluZyhzZWMpOwoKCgkJCgoJCQoKCQkvLyBwaXBlbGluZQoJCUlEYXRhQ3Vyc29yIHBpcGVsaW5l
Q3Vyc29yXzEgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCQlwaXBlbGluZUN1cnNvcl8xLmxhc3Qo
KTsKCQlwaXBlbGluZUN1cnNvcl8xLmluc2VydEFmdGVyKCAiU2VjIiwgZGlzcGxheVRpbWVTZWMp
OwoJCXBpcGVsaW5lQ3Vyc29yXzEuaW5zZXJ0QWZ0ZXIoICJNaW4iLCBkaXNwbGF5VGltZU1pbik7
CgkJcGlwZWxpbmVDdXJzb3JfMS5pbnNlcnRBZnRlciggIkhyIiwgZGlzcGxheVRpbWVIcik7CgkJ
cGlwZWxpbmVDdXJzb3JfMS5pbnNlcnRBZnRlciggIkRheSIsIGRpc3BsYXlUaW1lRGF5KTsKCQlw
aXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTsKCX0gY2F0Y2ggKEV4Y2VwdGlvbiBlKSB7CgkJdGhy
b3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIkVycm9yICIgKyBlKTsKCX0=</value>
</Values>
