<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">listFiles</value>
  <value name="encodeutf8">true</value>
  <value name="body">CUlEYXRhQ3Vyc29yIGlkY1BpcGVsaW5lID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CgoJU3RyaW5n
IGRpcmVjdG9yeSA9IG51bGw7CglpZiAoaWRjUGlwZWxpbmUuZmlyc3QoImRpcmVjdG9yeSIpKQoJ
ewoJCWRpcmVjdG9yeSA9IChTdHJpbmcpaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsKCX0KCWVsc2UK
CXsKCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiRGlyZWN0b3J5IGlzIG51bGwhIik7Cgl9
CgoJU3RyaW5nIHN0ckZpbGVTZXBhcmF0b3IgPSBTeXN0ZW0uZ2V0UHJvcGVydHkoImZpbGUuc2Vw
YXJhdG9yIik7CglpbnQgbnVtRmlsZXMgPSAwOwoKCUZpbGUgZGlyID0gbmV3IEZpbGUoZGlyZWN0
b3J5KTsKCglpZiAoIWRpci5leGlzdHMoKSB8fCAhZGlyLmlzRGlyZWN0b3J5KCkpCgl7CgkJdGhy
b3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIkVycm9yIHJlYWRpbmcgaW5ib3ggZGlyZWN0b3J5ISIp
OwoJfQoKCVN0cmluZyBkaXJfbGlzdFtdOwoJZGlyX2xpc3QgPSBkaXIubGlzdCgpOwoJaW50IG51
bV9maWxlc2FuZGRpciA9IGRpcl9saXN0Lmxlbmd0aDsKCglpZiAobnVtX2ZpbGVzYW5kZGlyIDwg
MSkJCS8vTm8gZmlsZXMgdG8gc2VuZAoJewoJCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJudW1G
aWxlcyIsIEludGVnZXIudG9TdHJpbmcobnVtRmlsZXMpKTsKCQlyZXR1cm47Cgl9CgoJLy9EZXRl
cm1pbmUgbnVtYmVyIG9mIGFjdHVhbCBmaWxlcwoJRmlsZSBjdXJyX2ZpbGU7Cglmb3IgKGludCBp
ID0gMDsgaSA8IG51bV9maWxlc2FuZGRpcjsgaSsrKQoJewoJCWN1cnJfZmlsZSA9IG5ldyBGaWxl
KGRpcmVjdG9yeSArIHN0ckZpbGVTZXBhcmF0b3IgKyBkaXJfbGlzdFtpXSk7CgkJaWYgKGN1cnJf
ZmlsZS5pc0ZpbGUoKSkKCQl7CgkJCW51bUZpbGVzKys7CgkJfQoJfQoJY3Vycl9maWxlID0gbnVs
bDsKIAoJLy9DcmVhdGUgYXJyYXkgd2l0aCBvbmx5IG5hbWVzIG9mIGZpbGVzIChleGNsdWRpbmcg
ZGlyZWN0b3JpZXMpCglTdHJpbmcgW10gZmlsZUxpc3QgPSBuZXcgU3RyaW5nW251bUZpbGVzXTsg
CglTdHJpbmcgW10gZmlsZUxpc3RfZnVsbHBhdGhuYW1lcyA9IG5ldyBTdHJpbmdbbnVtRmlsZXNd
OyAKCW51bUZpbGVzID0gMDsKCWZvciAoaW50IGkgPSAwOyBpIDwgbnVtX2ZpbGVzYW5kZGlyOyBp
KyspCgl7CgkJY3Vycl9maWxlID0gbmV3IEZpbGUoZGlyZWN0b3J5ICsgc3RyRmlsZVNlcGFyYXRv
ciArIGRpcl9saXN0W2ldKTsKCQlpZiAoY3Vycl9maWxlLmlzRmlsZSgpKQoJCXsKCQkJZmlsZUxp
c3RbbnVtRmlsZXNdID0gZGlyX2xpc3RbaV07CgoJCQkvLyBBc3NlbWJsZSBmdWxseSBxdWFsaWZp
ZWQgZmlsZW5hbWVzIChjaGVjayBVTklYICYgTlQpCgkJCWNoYXIgbGFzdENoYXIgPSBkaXJlY3Rv
cnkuY2hhckF0KGRpcmVjdG9yeS5sZW5ndGgoKSAtIDEpOwoJCQlpZiAoKGxhc3RDaGFyID09ICdc
XCcpIHx8IChsYXN0Q2hhciA9PSAnLycpKQoJCQl7CgkJCQlmaWxlTGlzdF9mdWxscGF0aG5hbWVz
W251bUZpbGVzXSA9IGRpcmVjdG9yeSArIGRpcl9saXN0W2ldOwoJCQl9CgkJCWVsc2UKCQkJewoJ
CQkJZmlsZUxpc3RfZnVsbHBhdGhuYW1lc1tudW1GaWxlc10gPSBkaXJlY3RvcnkgKyBzdHJGaWxl
U2VwYXJhdG9yICsgZGlyX2xpc3RbaV07CgkJCX0KCQkJbnVtRmlsZXMrKzsKCQl9Cgl9CgljdXJy
X2ZpbGUgPSBudWxsOwoKCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJudW1GaWxlcyIsIEludGVn
ZXIudG9TdHJpbmcobnVtRmlsZXMpKTsKCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJmaWxlTGlz
dCIsZmlsZUxpc3QpOwoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoImZpbGVMaXN0X2Z1bGxwYXRo
bmFtZXMiLGZpbGVMaXN0X2Z1bGxwYXRobmFtZXMpOwoJaWRjUGlwZWxpbmUuZGVzdHJveSgpOwo=
</value>
</Values>
